# Generated by Django 3.1.7 on 2021-03-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210324_0304'),
        ('departments', '0002_auto_20210324_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default='535e0a9d-b335-4d46-968d-bb74b8a31bd3',
                                    on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
    ]
