# Generated by Django 3.1.7 on 2021-03-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210324_0304'),
        ('departments', '0003_department_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company', verbose_name='Empresa'),
        ),
    ]
