# Generated by Django 3.1.7 on 2021-03-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210324_0304'),
        ('departments', '0004_auto_20210324_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ManyToManyField(to='companies.Company', verbose_name='Empresas'),
        ),
    ]
