# Generated by Django 3.1.7 on 2021-03-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20210324_0602'),
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime', to='employees.employee', verbose_name='Funcionário'),
        ),
    ]
