# Generated by Django 3.1.7 on 2021-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_auto_20210327_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
