# Generated by Django 3.1.7 on 2021-03-24 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('code', models.UUIDField(db_column='code_parameter', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aualizado em')),
                ('description', models.CharField(max_length=100, verbose_name='Descriação')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
