# Generated by Django 3.1.7 on 2021-03-27 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20210324_0602'),
        ('documents', '0002_auto_20210324_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Proprietário'),
        ),
    ]
