# Generated by Django 3.1.7 on 2021-03-24 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('companies', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='companies.company', verbose_name='Empresas')),
                ('departments', models.ManyToManyField(to='departments.Department')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
        ),
    ]
