# Generated by Django 3.1.7 on 2021-03-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='companies',
            new_name='company',
        ),
    ]
