# Generated by Django 3.1.7 on 2021-03-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0003_auto_20210324_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(to='departments.Department', verbose_name='Departamentos'),
        ),
    ]
