# Generated by Django 3.1.7 on 2021-03-24 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0004_auto_20210324_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Usuário'),
            preserve_default=False,
        ),
    ]
